/* Configuration for zode8 generated by Alire */
#ifndef ZODE8_CONFIG_H
#define ZODE8_CONFIG_H

#define CRATE_VERSION "1.0.2"
#define CRATE_NAME "zode8"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
